name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: '3 3 * * 2' # 3:03 AM, every Tuesday

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-podspec:
    name: Lint Podspec
    runs-on: macos-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to be able to find Git tags

      - name: Lint Podspec
        run: |
          set -eo pipefail
          export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          pod lib lint SwiftUIIntrospect.podspec --allow-warnings

  ci:
    name: ${{ matrix.platform[0] }} ${{ matrix.platform[1] }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: [visionOS, 1]
            runtime: visionOS 1.0
            os: macos-13
            xcode: 15.2
            install: true
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up pkgx environment
        uses: pkgxdev/setup@v1
        with:
          +: fastlane xcodes

      - name: Set environment variables
        run: echo "SKIP_SLOW_FASTLANE_WARNING=1" >> $GITHUB_ENV

      - if: ${{ matrix.platform[0] == 'visionOS' }}
        run: |
          defaults write com.apple.dt.Xcode AllowUnsupportedVisionOSHost -bool YES
          defaults write com.apple.CoreSimulator AllowUnsupportedVisionOSHost -bool YES

      - name: Select Xcode version
        run: sudo xcodes select ${{ matrix.xcode }}

      - if: ${{ matrix.install }}
        name: Install Required Runtime (${{ matrix.runtime }})
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: sudo xcodes runtimes install '${{ matrix.runtime }}'

      - if: true
        name: '[Debug] List Available Runtimes, Simulators, and Destinations'
        run: |
          xcrun simctl list
          xcodebuild -scheme "SwiftUIIntrospect" -showdestinations

      - if: ${{ matrix.platform[0] != 'watchOS' }}
        name: Build Showcase
        run: fastlane build platform:${{ matrix.platform[0] }} version:${{ matrix.platform[1] }} scheme:Showcase

      - if: ${{ matrix.platform[0] == 'watchOS' }}
        name: Build Library
        run: fastlane build platform:${{ matrix.platform[0] }} version:${{ matrix.platform[1] }} scheme:SwiftUIIntrospect

      - if: ${{ matrix.platform[0] != 'watchOS' }}
        name: Run Tests
        run: fastlane test platform:${{ matrix.platform[0] }} version:${{ matrix.platform[1] }} scheme:SwiftUIIntrospectTests configuration:Debug

      - if: ${{ matrix.platform[0] == 'iOS' && matrix.platform[1] <= '16' }}
        name: Run UI Tests
        run: fastlane test platform:${{ matrix.platform[0] }} version:${{ matrix.platform[1] }} scheme:SwiftUIIntrospectUITests configuration:Debug
